// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// RUN: onnx-mlir-opt --shape-inference --decompose-onnx="enable-convtranspose-phased enable-separate-phased-convs-for-convtranspose" %s -split-input-file | FileCheck %s

// Test that with enable-separate-phased-convs-for-convtranspose, the 4-phase
// kernel 6x6 case (which normally uses a single combined Conv) instead produces
// 4 separate Conv ops, concatenated and then merged back via
// Reshape->Transpose->Reshape.

// CHECK-LABEL:   func.func @test_sep_4phase_kernel_66(
// CHECK-SAME:                                         %[[VAL_0:.*]]: tensor<1x512x10x16xf32>,
// CHECK-SAME:                                         %[[VAL_1:.*]]: tensor<512x256x6x6xf32>) -> tensor<1x256x20x32xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 256, 20, 32]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 256, 10, 16]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<7> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[6, 7]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[7, 6]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<6> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_13:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_14:.*]] = onnx.Constant dense<6> : tensor<6xi64>
// CHECK:           %[[VAL_15:.*]] = onnx.Constant dense<2.000000e-02> : tensor<256xf32>
// CHECK:           %[[VAL_16:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<512x256x6x6xf32>) -> tensor<6x6x512x256xf32>
// CHECK:           %[[VAL_17:.*]] = "onnx.ReverseSequence"(%[[VAL_16]], %[[VAL_14]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<6x6x512x256xf32>, tensor<6xi64>) -> tensor<6x6x512x256xf32>
// CHECK:           %[[VAL_18:.*]] = "onnx.ReverseSequence"(%[[VAL_17]], %[[VAL_14]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<6x6x512x256xf32>, tensor<6xi64>) -> tensor<6x6x512x256xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Transpose"(%[[VAL_18]]) {perm = [2, 3, 0, 1]} : (tensor<6x6x512x256xf32>) -> tensor<512x256x6x6xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.Transpose"(%[[VAL_19]]) {perm = [1, 0, 2, 3]} : (tensor<512x256x6x6xf32>) -> tensor<256x512x6x6xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_11]], %[[VAL_10]], %[[VAL_13]], %[[VAL_12]]) : (tensor<256x512x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<256x512x3x3xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_9]], %[[VAL_8]], %[[VAL_13]], %[[VAL_12]]) : (tensor<256x512x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<256x512x3x3xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_7]], %[[VAL_6]], %[[VAL_13]], %[[VAL_12]]) : (tensor<256x512x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<256x512x3x3xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_5]], %[[VAL_4]], %[[VAL_13]], %[[VAL_12]]) : (tensor<256x512x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<256x512x3x3xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_24]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]} : (tensor<1x512x10x16xf32>, tensor<256x512x3x3xf32>, tensor<256xf32>) -> tensor<1x256x10x16xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_21]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]} : (tensor<1x512x10x16xf32>, tensor<256x512x3x3xf32>, tensor<256xf32>) -> tensor<1x256x10x16xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_22]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]} : (tensor<1x512x10x16xf32>, tensor<256x512x3x3xf32>, tensor<256xf32>) -> tensor<1x256x10x16xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_23]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]} : (tensor<1x512x10x16xf32>, tensor<256x512x3x3xf32>, tensor<256xf32>) -> tensor<1x256x10x16xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Concat"(%[[VAL_25]], %[[VAL_27]], %[[VAL_28]], %[[VAL_26]]) {axis = 1 : si64} : (tensor<1x256x10x16xf32>, tensor<1x256x10x16xf32>, tensor<1x256x10x16xf32>, tensor<1x256x10x16xf32>) -> tensor<1x1024x10x16xf32>
// CHECK:           %[[VAL_30:.*]] = "onnx.Reshape"(%[[VAL_29]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x1024x10x16xf32>, tensor<5xi64>) -> tensor<2x2x256x10x16xf32>
// CHECK:           %[[VAL_31:.*]] = "onnx.Transpose"(%[[VAL_30]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x256x10x16xf32>) -> tensor<256x10x2x16x2xf32>
// CHECK:           %[[VAL_32:.*]] = "onnx.Reshape"(%[[VAL_31]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<256x10x2x16x2xf32>, tensor<4xi64>) -> tensor<1x256x20x32xf32>
// CHECK:           onnx.Return %[[VAL_32]] : tensor<1x256x20x32xf32>
// CHECK:         }
func.func @test_sep_4phase_kernel_66(%arg0: tensor<1x512x10x16xf32>, %arg1: tensor<512x256x6x6xf32>) -> tensor<1x256x20x32xf32> {
  %0 = "onnx.Constant" () { value = dense<0.02> : tensor<256xf32> } : () -> tensor<256xf32>
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [6, 6], pads = [2, 2, 2, 2], strides = [2, 2]} : (tensor<1x512x10x16xf32>, tensor<512x256x6x6xf32>, tensor<256xf32>) -> tensor<1x256x20x32xf32>
  onnx.Return %1 : tensor<1x256x20x32xf32>

}

// -----

// Test kernel 2x2 case (also normally uses a single combined Conv, now forced
// to 4 separate convs, still merged with Reshape->Transpose->Reshape).


// CHECK-LABEL:   func.func @test_sep_4phase_kernel_22(
// CHECK-SAME:                                         %[[VAL_0:.*]]: tensor<1x64x8x8xf32>,
// CHECK-SAME:                                         %[[VAL_1:.*]]: tensor<64x32x2x2xf32>) -> tensor<1x32x16x16xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 32, 16, 16]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 32, 8, 8]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<3> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[3, 2]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = "onnx.NoValue"() {onnx_node_name = "onnx.NoValue_0", value} : () -> none
// CHECK:           %[[VAL_13:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<64x32x2x2xf32>) -> tensor<2x2x64x32xf32>
// CHECK:           %[[VAL_14:.*]] = "onnx.ReverseSequence"(%[[VAL_13]], %[[VAL_11]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<2x2x64x32xf32>, tensor<2xi64>) -> tensor<2x2x64x32xf32>
// CHECK:           %[[VAL_15:.*]] = "onnx.ReverseSequence"(%[[VAL_14]], %[[VAL_11]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<2x2x64x32xf32>, tensor<2xi64>) -> tensor<2x2x64x32xf32>
// CHECK:           %[[VAL_16:.*]] = "onnx.Transpose"(%[[VAL_15]]) {perm = [2, 3, 0, 1]} : (tensor<2x2x64x32xf32>) -> tensor<64x32x2x2xf32>
// CHECK:           %[[VAL_17:.*]] = "onnx.Transpose"(%[[VAL_16]]) {perm = [1, 0, 2, 3]} : (tensor<64x32x2x2xf32>) -> tensor<32x64x2x2xf32>
// CHECK:           %[[VAL_18:.*]] = "onnx.Slice"(%[[VAL_17]], %[[VAL_9]], %[[VAL_11]], %[[VAL_10]], %[[VAL_11]]) : (tensor<32x64x2x2xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x64x1x1xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Slice"(%[[VAL_17]], %[[VAL_8]], %[[VAL_7]], %[[VAL_10]], %[[VAL_11]]) : (tensor<32x64x2x2xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x64x1x1xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.Slice"(%[[VAL_17]], %[[VAL_6]], %[[VAL_10]], %[[VAL_10]], %[[VAL_11]]) : (tensor<32x64x2x2xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x64x1x1xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.Slice"(%[[VAL_17]], %[[VAL_5]], %[[VAL_4]], %[[VAL_10]], %[[VAL_11]]) : (tensor<32x64x2x2xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x64x1x1xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_21]], %[[VAL_12]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x64x8x8xf32>, tensor<32x64x1x1xf32>, none) -> tensor<1x32x8x8xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_18]], %[[VAL_12]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x64x8x8xf32>, tensor<32x64x1x1xf32>, none) -> tensor<1x32x8x8xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_19]], %[[VAL_12]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x64x8x8xf32>, tensor<32x64x1x1xf32>, none) -> tensor<1x32x8x8xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_20]], %[[VAL_12]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x64x8x8xf32>, tensor<32x64x1x1xf32>, none) -> tensor<1x32x8x8xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Concat"(%[[VAL_22]], %[[VAL_24]], %[[VAL_25]], %[[VAL_23]]) {axis = 1 : si64} : (tensor<1x32x8x8xf32>, tensor<1x32x8x8xf32>, tensor<1x32x8x8xf32>, tensor<1x32x8x8xf32>) -> tensor<1x128x8x8xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Reshape"(%[[VAL_26]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x128x8x8xf32>, tensor<5xi64>) -> tensor<2x2x32x8x8xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Transpose"(%[[VAL_27]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x32x8x8xf32>) -> tensor<32x8x2x8x2xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Reshape"(%[[VAL_28]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<32x8x2x8x2xf32>, tensor<4xi64>) -> tensor<1x32x16x16xf32>
// CHECK:           onnx.Return %[[VAL_29]] : tensor<1x32x16x16xf32>
// CHECK:         }
func.func @test_sep_4phase_kernel_22(%arg0: tensor<1x64x8x8xf32>, %arg1: tensor<64x32x2x2xf32>) -> tensor<1x32x16x16xf32> {
  %0 = "onnx.NoValue"() {onnx_node_name = "onnx.NoValue_0", value} : () -> none
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]} : (tensor<1x64x8x8xf32>, tensor<64x32x2x2xf32>, none) -> tensor<1x32x16x16xf32>
  onnx.Return %1 : tensor<1x32x16x16xf32>

}

// -----

// Test that the kernel 4x4 case (which already uses 4 separate convs) keeps
// producing 4 separate convs merged with Reshape->Transpose->Reshape.


// CHECK-LABEL:   func.func @test_sep_4phase_kernel_44(
// CHECK-SAME:                                         %[[VAL_0:.*]]: tensor<1x128x10x16xf32>,
// CHECK-SAME:                                         %[[VAL_1:.*]]: tensor<128x32x4x4xf32>) -> tensor<1x32x20x32xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 32, 20, 32]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 32, 10, 16]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<5> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[4, 5]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[5, 4]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<4> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_13:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_14:.*]] = onnx.Constant dense<4> : tensor<4xi64>
// CHECK:           %[[VAL_15:.*]] = onnx.Constant dense<2.000000e-02> : tensor<32xf32>
// CHECK:           %[[VAL_16:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<128x32x4x4xf32>) -> tensor<4x4x128x32xf32>
// CHECK:           %[[VAL_17:.*]] = "onnx.ReverseSequence"(%[[VAL_16]], %[[VAL_14]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<4x4x128x32xf32>, tensor<4xi64>) -> tensor<4x4x128x32xf32>
// CHECK:           %[[VAL_18:.*]] = "onnx.ReverseSequence"(%[[VAL_17]], %[[VAL_14]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<4x4x128x32xf32>, tensor<4xi64>) -> tensor<4x4x128x32xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Transpose"(%[[VAL_18]]) {perm = [2, 3, 0, 1]} : (tensor<4x4x128x32xf32>) -> tensor<128x32x4x4xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.Transpose"(%[[VAL_19]]) {perm = [1, 0, 2, 3]} : (tensor<128x32x4x4xf32>) -> tensor<32x128x4x4xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_11]], %[[VAL_10]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_9]], %[[VAL_8]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_7]], %[[VAL_6]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_5]], %[[VAL_4]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_24]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 0, 1, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_21]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 1, 0, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_22]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 1, 1, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_23]], %[[VAL_15]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 0, 0, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Concat"(%[[VAL_26]], %[[VAL_28]], %[[VAL_27]], %[[VAL_25]]) {axis = 1 : si64} : (tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>) -> tensor<1x128x10x16xf32>
// CHECK:           %[[VAL_30:.*]] = "onnx.Reshape"(%[[VAL_29]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x128x10x16xf32>, tensor<5xi64>) -> tensor<2x2x32x10x16xf32>
// CHECK:           %[[VAL_31:.*]] = "onnx.Transpose"(%[[VAL_30]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x32x10x16xf32>) -> tensor<32x10x2x16x2xf32>
// CHECK:           %[[VAL_32:.*]] = "onnx.Reshape"(%[[VAL_31]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<32x10x2x16x2xf32>, tensor<4xi64>) -> tensor<1x32x20x32xf32>
// CHECK:           onnx.Return %[[VAL_32]] : tensor<1x32x20x32xf32>
// CHECK:         }
func.func @test_sep_4phase_kernel_44(%arg0: tensor<1x128x10x16xf32>, %arg1: tensor<128x32x4x4xf32>) -> tensor<1x32x20x32xf32> {
  %0 = "onnx.Constant" () { value = dense<0.02> : tensor<32xf32> } : () -> tensor<32xf32>
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]} : (tensor<1x128x10x16xf32>, tensor<128x32x4x4xf32>, tensor<32xf32>) -> tensor<1x32x20x32xf32>
  onnx.Return %1 : tensor<1x32x20x32xf32>

}

// -----

// Test k3x3 with pads [0,0,1,1] (weights padded to 4x4). With non-uniform
// per-phase padding, conv outputs are correct size directly (no slicing of the
// activations), still merged with Reshape->Transpose->Reshape.


// CHECK-LABEL:   func.func @test_sep_4phase_pads_0011(
// CHECK-SAME:                                         %[[VAL_0:.*]]: tensor<1x128x10x16xf32>,
// CHECK-SAME:                                         %[[VAL_1:.*]]: tensor<128x32x3x3xf32>) -> tensor<1x32x20x32xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 32, 20, 32]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 32, 10, 16]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<5> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[4, 5]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[5, 4]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<4> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_13:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_14:.*]] = "onnx.NoValue"() {value} : () -> none
// CHECK:           %[[VAL_15:.*]] = onnx.Constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[VAL_16:.*]] = onnx.Constant dense<[0, 0, 0, 0, 0, 0, 1, 1]> : tensor<8xi64>
// CHECK:           %[[VAL_17:.*]] = onnx.Constant dense<3> : tensor<3xi64>
// CHECK:           %[[VAL_18:.*]] = onnx.Constant dense<2.000000e-02> : tensor<32xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<128x32x3x3xf32>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.ReverseSequence"(%[[VAL_19]], %[[VAL_17]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<3x3x128x32xf32>, tensor<3xi64>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.ReverseSequence"(%[[VAL_20]], %[[VAL_17]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<3x3x128x32xf32>, tensor<3xi64>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Transpose"(%[[VAL_21]]) {perm = [2, 3, 0, 1]} : (tensor<3x3x128x32xf32>) -> tensor<128x32x3x3xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Transpose"(%[[VAL_22]]) {perm = [1, 0, 2, 3]} : (tensor<128x32x3x3xf32>) -> tensor<32x128x3x3xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Pad"(%[[VAL_23]], %[[VAL_16]], %[[VAL_15]], %[[VAL_14]]) {mode = "constant"} : (tensor<32x128x3x3xf32>, tensor<8xi64>, tensor<f32>, none) -> tensor<32x128x4x4xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_11]], %[[VAL_10]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_9]], %[[VAL_8]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_7]], %[[VAL_6]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_5]], %[[VAL_4]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_28]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 0, 1, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_30:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_25]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 1, 0, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_31:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_26]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 1, 1, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_32:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_27]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 0, 0, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_33:.*]] = "onnx.Concat"(%[[VAL_30]], %[[VAL_32]], %[[VAL_31]], %[[VAL_29]]) {axis = 1 : si64} : (tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>) -> tensor<1x128x10x16xf32>
// CHECK:           %[[VAL_34:.*]] = "onnx.Reshape"(%[[VAL_33]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x128x10x16xf32>, tensor<5xi64>) -> tensor<2x2x32x10x16xf32>
// CHECK:           %[[VAL_35:.*]] = "onnx.Transpose"(%[[VAL_34]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x32x10x16xf32>) -> tensor<32x10x2x16x2xf32>
// CHECK:           %[[VAL_36:.*]] = "onnx.Reshape"(%[[VAL_35]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<32x10x2x16x2xf32>, tensor<4xi64>) -> tensor<1x32x20x32xf32>
// CHECK:           onnx.Return %[[VAL_36]] : tensor<1x32x20x32xf32>
// CHECK:         }
func.func @test_sep_4phase_pads_0011(%arg0: tensor<1x128x10x16xf32>, %arg1: tensor<128x32x3x3xf32>) -> tensor<1x32x20x32xf32> {
  %0 = "onnx.Constant" () { value = dense<0.02> : tensor<32xf32> } : () -> tensor<32xf32>
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [0, 0, 1, 1], strides = [2, 2]} : (tensor<1x128x10x16xf32>, tensor<128x32x3x3xf32>, tensor<32xf32>) -> tensor<1x32x20x32xf32>
  onnx.Return %1 : tensor<1x32x20x32xf32>

}

// -----

// Test k3x3 with pads [1,1,0,0] (weights padded to 4x4). Same as above
// but with different weight padding direction.


// CHECK-LABEL:   func.func @test_sep_4phase_pads_1100(
// CHECK-SAME:                                         %[[VAL_0:.*]]: tensor<1x128x10x16xf32>,
// CHECK-SAME:                                         %[[VAL_1:.*]]: tensor<128x32x3x3xf32>) -> tensor<1x32x20x32xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 32, 20, 32]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 32, 10, 16]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<5> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[4, 5]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[5, 4]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<4> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_13:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_14:.*]] = "onnx.NoValue"() {value} : () -> none
// CHECK:           %[[VAL_15:.*]] = onnx.Constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[VAL_16:.*]] = onnx.Constant dense<[0, 0, 1, 1, 0, 0, 0, 0]> : tensor<8xi64>
// CHECK:           %[[VAL_17:.*]] = onnx.Constant dense<3> : tensor<3xi64>
// CHECK:           %[[VAL_18:.*]] = onnx.Constant dense<2.000000e-02> : tensor<32xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<128x32x3x3xf32>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.ReverseSequence"(%[[VAL_19]], %[[VAL_17]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<3x3x128x32xf32>, tensor<3xi64>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.ReverseSequence"(%[[VAL_20]], %[[VAL_17]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<3x3x128x32xf32>, tensor<3xi64>) -> tensor<3x3x128x32xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Transpose"(%[[VAL_21]]) {perm = [2, 3, 0, 1]} : (tensor<3x3x128x32xf32>) -> tensor<128x32x3x3xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Transpose"(%[[VAL_22]]) {perm = [1, 0, 2, 3]} : (tensor<128x32x3x3xf32>) -> tensor<32x128x3x3xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Pad"(%[[VAL_23]], %[[VAL_16]], %[[VAL_15]], %[[VAL_14]]) {mode = "constant"} : (tensor<32x128x3x3xf32>, tensor<8xi64>, tensor<f32>, none) -> tensor<32x128x4x4xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_11]], %[[VAL_10]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_9]], %[[VAL_8]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_7]], %[[VAL_6]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Slice"(%[[VAL_24]], %[[VAL_5]], %[[VAL_4]], %[[VAL_13]], %[[VAL_12]]) : (tensor<32x128x4x4xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<32x128x2x2xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_28]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 0, 1, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_30:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_25]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 1, 0, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_31:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_26]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [0, 1, 1, 0], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_32:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_27]], %[[VAL_18]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [2, 2], pads = [1, 0, 0, 1], strides = [1, 1]} : (tensor<1x128x10x16xf32>, tensor<32x128x2x2xf32>, tensor<32xf32>) -> tensor<1x32x10x16xf32>
// CHECK:           %[[VAL_33:.*]] = "onnx.Concat"(%[[VAL_30]], %[[VAL_32]], %[[VAL_31]], %[[VAL_29]]) {axis = 1 : si64} : (tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>, tensor<1x32x10x16xf32>) -> tensor<1x128x10x16xf32>
// CHECK:           %[[VAL_34:.*]] = "onnx.Reshape"(%[[VAL_33]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x128x10x16xf32>, tensor<5xi64>) -> tensor<2x2x32x10x16xf32>
// CHECK:           %[[VAL_35:.*]] = "onnx.Transpose"(%[[VAL_34]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x32x10x16xf32>) -> tensor<32x10x2x16x2xf32>
// CHECK:           %[[VAL_36:.*]] = "onnx.Reshape"(%[[VAL_35]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<32x10x2x16x2xf32>, tensor<4xi64>) -> tensor<1x32x20x32xf32>
// CHECK:           onnx.Return %[[VAL_36]] : tensor<1x32x20x32xf32>
// CHECK:         }
func.func @test_sep_4phase_pads_1100(%arg0: tensor<1x128x10x16xf32>, %arg1: tensor<128x32x3x3xf32>) -> tensor<1x32x20x32xf32> {
  %0 = "onnx.Constant" () { value = dense<0.02> : tensor<32xf32> } : () -> tensor<32xf32>
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 0, 0], strides = [2, 2]} : (tensor<1x128x10x16xf32>, tensor<128x32x3x3xf32>, tensor<32xf32>) -> tensor<1x32x20x32xf32>
  onnx.Return %1 : tensor<1x32x20x32xf32>

}

// -----

// Test that even with enable-separate-phased-convs-for-convtranspose, a 4-phase
// kernel 6x6 ConvTranspose whose output channels are NOT DMA-aligned (here a
// single output channel) still combines the 4 phased weights into a single
// Conv (weights concatenated to 4x32x3x3), since the separate-conv path is only
// taken when output channels are DMA-aligned. Shapes taken from the asura
// asura_convt_outc1 model. Note the single combined Conv producing 4 channels.

// CHECK-LABEL:   func.func @test_sep_4phase_kernel_66_unaligned_oc(
// CHECK-SAME:                                                      %[[VAL_0:.*]]: tensor<1x32x80x336xf32>,
// CHECK-SAME:                                                      %[[VAL_1:.*]]: tensor<32x1x6x6xf32>) -> tensor<1x1x160x672xf32> {
// CHECK:           %[[VAL_2:.*]] = onnx.Constant dense<[1, 1, 160, 672]> : tensor<4xi64>
// CHECK:           %[[VAL_3:.*]] = onnx.Constant dense<[2, 2, 1, 80, 336]> : tensor<5xi64>
// CHECK:           %[[VAL_4:.*]] = onnx.Constant dense<7> : tensor<2xi64>
// CHECK:           %[[VAL_5:.*]] = onnx.Constant dense<1> : tensor<2xi64>
// CHECK:           %[[VAL_6:.*]] = onnx.Constant dense<[6, 7]> : tensor<2xi64>
// CHECK:           %[[VAL_7:.*]] = onnx.Constant dense<[0, 1]> : tensor<2xi64>
// CHECK:           %[[VAL_8:.*]] = onnx.Constant dense<[7, 6]> : tensor<2xi64>
// CHECK:           %[[VAL_9:.*]] = onnx.Constant dense<[1, 0]> : tensor<2xi64>
// CHECK:           %[[VAL_10:.*]] = onnx.Constant dense<6> : tensor<2xi64>
// CHECK:           %[[VAL_11:.*]] = onnx.Constant dense<0> : tensor<2xi64>
// CHECK:           %[[VAL_12:.*]] = onnx.Constant dense<2> : tensor<2xi64>
// CHECK:           %[[VAL_13:.*]] = onnx.Constant dense<[2, 3]> : tensor<2xi64>
// CHECK:           %[[VAL_14:.*]] = onnx.Constant dense<6> : tensor<6xi64>
// CHECK:           %[[VAL_15:.*]] = onnx.Constant dense<2.000000e-02> : tensor<1xf32>
// CHECK:           %[[VAL_16:.*]] = "onnx.Transpose"(%[[VAL_1]]) {perm = [2, 3, 0, 1]} : (tensor<32x1x6x6xf32>) -> tensor<6x6x32x1xf32>
// CHECK:           %[[VAL_17:.*]] = "onnx.ReverseSequence"(%[[VAL_16]], %[[VAL_14]]) {batch_axis = 1 : si64, time_axis = 0 : si64} : (tensor<6x6x32x1xf32>, tensor<6xi64>) -> tensor<6x6x32x1xf32>
// CHECK:           %[[VAL_18:.*]] = "onnx.ReverseSequence"(%[[VAL_17]], %[[VAL_14]]) {batch_axis = 0 : si64, time_axis = 1 : si64} : (tensor<6x6x32x1xf32>, tensor<6xi64>) -> tensor<6x6x32x1xf32>
// CHECK:           %[[VAL_19:.*]] = "onnx.Transpose"(%[[VAL_18]]) {perm = [2, 3, 0, 1]} : (tensor<6x6x32x1xf32>) -> tensor<32x1x6x6xf32>
// CHECK:           %[[VAL_20:.*]] = "onnx.Transpose"(%[[VAL_19]]) {perm = [1, 0, 2, 3]} : (tensor<32x1x6x6xf32>) -> tensor<1x32x6x6xf32>
// CHECK:           %[[VAL_21:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_11]], %[[VAL_10]], %[[VAL_13]], %[[VAL_12]]) : (tensor<1x32x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<1x32x3x3xf32>
// CHECK:           %[[VAL_22:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_9]], %[[VAL_8]], %[[VAL_13]], %[[VAL_12]]) : (tensor<1x32x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<1x32x3x3xf32>
// CHECK:           %[[VAL_23:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_7]], %[[VAL_6]], %[[VAL_13]], %[[VAL_12]]) : (tensor<1x32x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<1x32x3x3xf32>
// CHECK:           %[[VAL_24:.*]] = "onnx.Slice"(%[[VAL_20]], %[[VAL_5]], %[[VAL_4]], %[[VAL_13]], %[[VAL_12]]) : (tensor<1x32x6x6xf32>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>, tensor<2xi64>) -> tensor<1x32x3x3xf32>
// CHECK:           %[[VAL_25:.*]] = "onnx.Concat"(%[[VAL_24]], %[[VAL_22]], %[[VAL_23]], %[[VAL_21]]) {axis = 0 : si64} : (tensor<1x32x3x3xf32>, tensor<1x32x3x3xf32>, tensor<1x32x3x3xf32>, tensor<1x32x3x3xf32>) -> tensor<4x32x3x3xf32>
// CHECK:           %[[VAL_26:.*]] = "onnx.Concat"(%[[VAL_15]], %[[VAL_15]], %[[VAL_15]], %[[VAL_15]]) {axis = 0 : si64} : (tensor<1xf32>, tensor<1xf32>, tensor<1xf32>, tensor<1xf32>) -> tensor<4xf32>
// CHECK:           %[[VAL_27:.*]] = "onnx.Conv"(%[[VAL_0]], %[[VAL_25]], %[[VAL_26]]) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]} : (tensor<1x32x80x336xf32>, tensor<4x32x3x3xf32>, tensor<4xf32>) -> tensor<1x4x80x336xf32>
// CHECK:           %[[VAL_28:.*]] = "onnx.Reshape"(%[[VAL_27]], %[[VAL_3]]) {allowzero = 0 : si64} : (tensor<1x4x80x336xf32>, tensor<5xi64>) -> tensor<2x2x1x80x336xf32>
// CHECK:           %[[VAL_29:.*]] = "onnx.Transpose"(%[[VAL_28]]) {perm = [2, 3, 0, 4, 1]} : (tensor<2x2x1x80x336xf32>) -> tensor<1x80x2x336x2xf32>
// CHECK:           %[[VAL_30:.*]] = "onnx.Reshape"(%[[VAL_29]], %[[VAL_2]]) {allowzero = 0 : si64} : (tensor<1x80x2x336x2xf32>, tensor<4xi64>) -> tensor<1x1x160x672xf32>
// CHECK:           onnx.Return %[[VAL_30]] : tensor<1x1x160x672xf32>
// CHECK:         }
func.func @test_sep_4phase_kernel_66_unaligned_oc(%arg0: tensor<1x32x80x336xf32>, %arg1: tensor<32x1x6x6xf32>) -> tensor<1x1x160x672xf32> {
  %0 = "onnx.Constant" () { value = dense<0.02> : tensor<1xf32> } : () -> tensor<1xf32>
  %1 = "onnx.ConvTranspose"(%arg0, %arg1, %0) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : si64, kernel_shape = [6, 6], pads = [2, 2, 2, 2], strides = [2, 2]} : (tensor<1x32x80x336xf32>, tensor<32x1x6x6xf32>, tensor<1xf32>) -> tensor<1x1x160x672xf32>
  onnx.Return %1 : tensor<1x1x160x672xf32>

}
